### ISSUE TITLE
Problem with automated deploy

### ISSUE THREAD

**Issue by lnmunhoz** [nielsenramon/kickster#17]
I'm getting the following error in the Circle CI build:
`bash: line 1: ./bin/automated: Permission denied Action failed: ./bin/automated`

How to fix this?

circle.yml
```
machine:
  environment:
    USER_NAME: lnmunhoz
    USER_EMAIL: ln.munhoz@gmail.com
  ruby:
    version: 2.2.3

dependencies:
  pre:
    - ./bin/setup

deployment:
  production:
    branch: master
    commands:
      - ./bin/automated
```

automated
```
#!/bin/bash

# Automated deploy script with Circle CI.

# Exit if any subcommand fails.
set -e

# Variables
ORIGIN_URL=`git config --get remote.origin.url`

echo "Started deploying"

# Checkout gh-pages branch.
if [ `git branch | grep gh-pages` ]
then
  git branch -D gh-pages
fi
git checkout -b gh-pages

# Build site.
bundle exec jekyll build

# Delete and move files.
find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
mv _site/* .
rm -R _site/

# Push to gh-pages.
git config user.name "$USER_NAME"
git config user.email "$USER_EMAIL"

git add -fA
git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
git push -f $ORIGIN_URL gh-pages

# Move back to previous branch.
git checkout -

echo "Deployed Successfully!"

exit 0
```
